Refactor help and function calling
- Automatically include all filedb functions
- Do not include unimplemented methods in calling or help

diff --git a/filedb b/filedb
--- a/filedb
+++ b/filedb
@@ -73,14 +73,14 @@ fn-help() {
   declare desc="shows help information"
   echo "filedb $FILEDB_VERSION"
   echo ""
-  fn-info "filedb-blank"
-  fn-info "filedb-del"
-  fn-info "filedb-exists"
-  fn-info "filedb-get"
-  fn-info "filedb-set"
-  fn-info "filedb-set-from-file"
 
-  fn-info "filedb-flush-domain"
+  for fn in $(declare -F | grep -oEi "filedb-([a-z-]+)"); do
+    local UNIMPLEMENTED=false
+    eval "$(type "$fn" | grep UNIMPLEMENTED | head -1)";
+    if [[ "$UNIMPLEMENTED" == "false" ]]; then
+      fn-info "$fn"
+    fi
+  done
 }
 
 filedb-blank() {
@@ -258,51 +258,19 @@ filedb-flush-domain() {
 }
 
 main() {
+  declare desc="main input function"
+  declare CMD="$1"
+  local exit_code=1
+
   if [[ -z "$1" ]]; then
     fn-help
     exit 0
   fi
 
-  local cmd="$1"
   shift 1
 
   set +e;
-  case "$cmd" in
-    blank)
-      filedb-blank "$@"
-      exit_code="$?"
-      ;;
-
-    del)
-      filedb-del "$@"
-      exit_code="$?"
-      ;;
-
-    exists)
-      filedb-exists "$@"
-      exit_code="$?"
-      ;;
-
-    get)
-      filedb-get "$@"
-      exit_code="$?"
-      ;;
-
-    set)
-      filedb-set "$@"
-      exit_code="$?"
-      ;;
-
-    set-from-file)
-      filedb-set-from-file "$@"
-      exit_code="$?"
-      ;;
-
-    flush-domain)
-      filedb-flush-domain "$@"
-      exit_code="$?"
-      ;;
-
+  case "$CMD" in
     help)
       if [[ -z $1 ]]; then
         fn-help
@@ -319,8 +287,26 @@ main() {
       ;;
 
     *)
-      log-fail "invalid command"
-      exit_code="1"
+      local executed=false
+      for fn in $(declare -F | grep -oEi "filedb-([a-z-]+)"); do
+        if [[ "$fn" == "filedb-$CMD" ]]; then
+          local UNIMPLEMENTED=false
+          eval "$(type "$fn" | grep UNIMPLEMENTED | head -1)";
+
+          if [[ "$UNIMPLEMENTED" == "false" ]]; then
+            local executed=true
+            $fn "$@"
+            exit_code="$?"
+          fi
+
+          break
+        fi
+      done
+
+      if [[ $executed == "false" ]]; then
+        log-fail "invalid command"
+        exit_code="1"
+      fi
       ;;
   esac
   set -e
